server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
